#!/bin/sh

pt=mail.yandex.ru
geth=$(ip link | awk -F: '$0 !~ "lo|vir|wl|^[^0-9]"{print $2;getline}')
ping -c1 -I $geth $pt &> /dev/null
if [ $? -eq 0 ]; then
	sudo nmcli radio wifi off
else
	echo 0 > /dev/null
fi